version: "3.9"
services:
  postgresql-db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passw0rd"
    volumes:
      - ./configs/db:/docker-entrypoint-initdb.d/

#  not needed - due to fact that I will use only one DB - and sync is not needed
#  zookeeper:
#    image: zookeeper:latest
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeper
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
